id: P2A681DD6
initial_creation_type: ocr
source_metadata:
  volumes:
    f5ceec05d21a4af6823d7ffd634bee6b:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: རྡོ་རྗེའི་སྨོན་ལམ།
      total_pages: 1880
      volume_number: 116
